/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cvstool.h"

bool_t
xdr_cvstool_status (XDR *xdrs, cvstool_status *objp)
{
	register int32_t *buf;

	 if (!xdr_enum (xdrs, (enum_t *) objp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_path (XDR *xdrs, cvstool_path *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, CVSTOOL_PATHLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_name (XDR *xdrs, cvstool_name *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, CVSTOOL_NAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_ver (XDR *xdrs, cvstool_ver *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, CVSTOOL_VERLEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_date (XDR *xdrs, cvstool_date *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, CVSTOOL_DATELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_ls_args (XDR *xdrs, cvstool_ls_args *objp)
{
	register int32_t *buf;

	 if (!xdr_cvstool_path (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->option))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_resp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_ver_info (XDR *xdrs, cvstool_ver_info *objp)
{
	register int32_t *buf;

	 if (!xdr_cvstool_ver (xdrs, &objp->ver))
		 return FALSE;
	 if (!xdr_cvstool_name (xdrs, &objp->author))
		 return FALSE;
	 if (!xdr_cvstool_date (xdrs, &objp->date))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (cvstool_ver_info), (xdrproc_t) xdr_cvstool_ver_info))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_dirent (XDR *xdrs, cvstool_dirent *objp)
{
	register int32_t *buf;

	 if (!xdr_cvstool_name (xdrs, &objp->name))
		 return FALSE;
	 if (!xdr_cvstool_ver_info (xdrs, &objp->ver_info))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->next, sizeof (cvstool_dirent), (xdrproc_t) xdr_cvstool_dirent))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_ls_resp (XDR *xdrs, cvstool_ls_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num_resp))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->dirents, sizeof (cvstool_dirent), (xdrproc_t) xdr_cvstool_dirent))
		 return FALSE;
	 if (!xdr_cvstool_status (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_lsver_args (XDR *xdrs, cvstool_lsver_args *objp)
{
	register int32_t *buf;

	 if (!xdr_cvstool_path (xdrs, &objp->path))
		 return FALSE;
	 if (!xdr_cvstool_ver (xdrs, &objp->from_ver))
		 return FALSE;
	 if (!xdr_u_int (xdrs, &objp->option))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num_resp))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_cvstool_lsver_resp (XDR *xdrs, cvstool_lsver_resp *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num_resp))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->vers, sizeof (cvstool_ver_info), (xdrproc_t) xdr_cvstool_ver_info))
		 return FALSE;
	 if (!xdr_cvstool_status (xdrs, &objp->status))
		 return FALSE;
	return TRUE;
}
