#ifndef __NFS_REDEF_H
#define __NFS_REDEF_H

//#define nfs_program_2 
#define nfsproc_null_2_svc nfsproc_null_2
#define nfsproc_getattr_2_svc nfsproc_getattr_2
#define nfsproc_setattr_2_svc nfsproc_setattr_2
#define nfsproc_root_2_svc nfsproc_root_2
#define nfsproc_lookup_2_svc nfsproc_lookup_2
#define nfsproc_readlink_2_svc nfsproc_readlink_2
#define nfsproc_read_2_svc nfsproc_read_2
#define nfsproc_writecache_2_svc nfsproc_writecache_2
#define nfsproc_write_2_svc nfsproc_write_2
#define nfsproc_create_2_svc nfsproc_create_2
#define nfsproc_remove_2_svc nfsproc_remove_2
#define nfsproc_rename_2_svc nfsproc_rename_2
#define nfsproc_link_2_svc nfsproc_link_2
#define nfsproc_symlink_2_svc nfsproc_symlink_2
#define nfsproc_mkdir_2_svc nfsproc_mkdir_2
#define nfsproc_rmdir_2_svc nfsproc_rmdir_2
#define nfsproc_readdir_2_svc nfsproc_readdir_2
#define nfsproc_statfs_2_svc nfsproc_statfs_2
//#define adm_program_2 
#define admproc_null_2_svc admproc_null_2
#define admproc_attach_2_svc admproc_attach_2
#define admproc_detach_2_svc admproc_detach_2

#endif
